export {default as About} from './About/About'
export {default as Portfolio} from './Portfolio/Portfolio'
export {default as Education} from './Education/Education'
export {default as Skills} from './Skills/Skills'
export {default as Contact} from './Contact/Contact'